[Random Nonsense]
type=DemoDevice

# # # This will automatically create all the devices found in your YoLink account as new subdevices
# [YoLinkService]
# device.key= Your UAC key here
# device.user_id=Your UAC password here
# type = YoLinkService

# # Hide this, it just creates the subdevices
# hidden = True

# # This is not a real device entry.  It is extra configuration for a subdevice
# # created by the YoLinkService.  Note the lack of a type field, and the name that matches a subdevice that 
# [YoLinkService.Bedroom]
# title = Bedroom Sensor
