import json
import re
import traceback
import inspect
from iot_devices.host import get_class, discover
from iot_devices.device import Device


def print_datapoints(f: str):
    x = re.findall(r"\.((\w*)_data_point\(\s*(.[^,]*)[,\)][^\)]*\))", f)

    print("## Datapoints(Some may be unlisted)\n")
    for i in x:
        if i[1] not in ("numeric", "string", "bool", "object", "bytestream"):
            continue
        subtype = re.findall(r"subtype\s*=\s*['\"](.*?)['\"]", i[0])
        if subtype:
            subtype = subtype[0]
        else:
            subtype = ""

        w = "writable=false" in i[0].lower().replace(" ", "")
        print(f"# {i[1]} {subtype} {i[2]}  {'(writable)' if not w else ''}")

    print("")


print("# Known Device Plugins\n")
print("All devices shown, some config params may be unlisted.")
print("This documentation is autogenerated with iot_devices_scan.py\n")
d = discover()
for i in sorted(d.keys()):
    print("## " + i + "\n")
    print(d[i].get("description", "") + "\n")
    try:
        c1 = get_class({"type": i})

        dpi = {}
        dpd = {}
        dpw = {}

        props = {}

        class c(c1):
            def string_data_point(
                self,
                name: str,
                description: str = "",
                unit: str = "",
                handler=None,
                interval: float = 0,
                writable=True,
                subtype: str = "",
                **kwargs,
            ):
                Device.string_data_point(
                    self,
                    name,
                    description=description,
                    unit=unit,
                    handler=handler,
                    interval=interval,
                    writable=writable,
                    subtype=subtype,
                    **kwargs,
                )
                dpi[name] = f"{subtype} {unit}"
                dpd[name] = description
                dpw[name] = writable

            def numeric_data_point(
                self,
                name: str,
                description: str = "",
                unit: str = "",
                handler=None,
                interval: float = 0,
                writable=True,
                subtype: str = "",
                **kwargs,
            ):
                Device.numeric_data_point(
                    self,
                    name,
                    description=description,
                    unit=unit,
                    handler=handler,
                    interval=interval,
                    writable=writable,
                    subtype=subtype,
                    **kwargs,
                )
                dpi[name] = f"""{subtype} {unit}""".strip()
                dpd[name] = description
                dpw[name] = writable

        defaults = {}
        tags = {}

        if not c.json_schema:
            try:
                inst = c("DeviceName", {"type": i})
                props.update(inst.config_properties.raw)

                for j in inst.config:
                    if not j in props:
                        props[j] = {}

                tags.update(inst.datapoints)

            except Exception:
                print(traceback.format_exc())

            print("```python")
            print("from iot_devices.host import create_device")
            print("from " + d[i]["importable"] + " import " + i + "\n")

            print("dev = " + "create_device(" + i + ', "name", {')
            count = 0

            for j in props:
                count += 1
                if j.startswith("device."):
                    desc = props[j].get("description", "")
                    if desc:
                        print("    # " + props[j].get("description", "") + "")
                    ending = "," if count < len(props) else "\n})"
                    if j in inst.config:
                        print(f"    '{j}': '{inst.config[j]}'" + ending)
            if not props:
                print("})")
        else:
            print("```python")
            print("from iot_devices.host import create_device")
            print("from " + d[i]["importable"] + " import " + i + "\n")

            print("dev = " + "create_device(" + i + ', "name", cfg)')

            sch = json.dumps(c.json_schema, indent=4)
            print("\n\n# Config Schema")
            for line in sch.split("\n"):
                print(f"# {line}")

            print_datapoints(inspect.getsource(c1))

        print("```")

    except Exception:
        print("## Error getting data for " + i)
        print(traceback.format_exc())

    print("")
